# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Stuffed Can
tagline:             'How much can you stuff?'
description:         'Blog about Stuff'
url:                 http://stuffedcan.com
baseurl:             'http://stuffedcan.com'
paginate:            5

# Custom vars
version:             1.0.3