# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Nídia Trovão
tagline:             Website
url:                 http://nidiatrovao.com
paginate:            3
baseurl:             "http://nidiatrovao.com"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
  
pages_list:       
  About: '/about'
  Research: '/research'
  Publications: '/publications'
