permalink:           /:categories/:title/

title:               StuffedCan
url:                 https://stuffedcan.github.io
paginate:            4

description: 'StuffedCan is where you find tips and tutorials about technology'

timezone: America/New_York

highlighter: rouge

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:
  Web: '/web'
  Software: '/software'
  Hardware: '/hardware'
  About: '/about'

#plugins:
#  - jekyll-sitemap
