# Site settings
title:        "Stuffed Can"
description:  "A blog about stuff... in a can."
baseurl:      ""
url:          "http://stuffedcan.com"
permalink:    /:title
github:       "yourusername"
twitter:      "yourusername"
email:        "mail@example.com"
disqus-id:    "example" #leave blank if you dont want comments.

# Build settings
markdown:     kramdown
sass:
    style: :compressed
